[2024-11-06T11:53:46.507+0000] {processor.py:161} INFO - Started process (PID=1607) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:53:46.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:53:46.511+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:53:46.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:53:46.515+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:53:46.514+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 54
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:53:46.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:53:46.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T11:54:07.562+0000] {processor.py:161} INFO - Started process (PID=1659) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:54:07.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:54:07.566+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:07.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:07.571+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:07.569+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 55
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:54:07.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:07.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.059 seconds
[2024-11-06T11:54:21.167+0000] {processor.py:161} INFO - Started process (PID=1685) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:54:21.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:54:21.171+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:21.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:21.176+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:21.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 56
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:54:21.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:21.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T11:54:25.235+0000] {processor.py:161} INFO - Started process (PID=1686) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:54:25.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:54:25.241+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:25.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:25.248+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:25.246+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 56
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:54:25.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:25.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T11:54:29.099+0000] {processor.py:161} INFO - Started process (PID=1702) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:54:29.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:54:29.104+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:29.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:29.109+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:29.108+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 56
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:54:29.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:29.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.047 seconds
[2024-11-06T11:54:33.199+0000] {processor.py:161} INFO - Started process (PID=1722) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:54:33.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:54:33.203+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:33.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:33.208+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:54:33.207+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 56
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:54:33.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:54:33.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2024-11-06T11:55:03.831+0000] {processor.py:161} INFO - Started process (PID=1798) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:55:03.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:55:03.841+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:03.841+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:03.848+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:03.846+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 56
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:55:03.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:03.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.063 seconds
[2024-11-06T11:55:29.952+0000] {processor.py:161} INFO - Started process (PID=1846) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:55:29.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:55:29.956+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:29.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:29.961+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:29.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 23
    return data
    ^
SyntaxError: invalid syntax
[2024-11-06T11:55:29.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:29.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2024-11-06T11:55:34.891+0000] {processor.py:161} INFO - Started process (PID=1878) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:55:34.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:55:34.896+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:34.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:34.902+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:34.900+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 57
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:55:34.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:34.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.052 seconds
[2024-11-06T11:55:40.350+0000] {processor.py:161} INFO - Started process (PID=1894) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:55:40.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:55:40.355+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:40.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:40.360+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:55:40.359+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 58
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:55:40.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:55:40.391+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.047 seconds
[2024-11-06T11:56:10.902+0000] {processor.py:161} INFO - Started process (PID=1972) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:10.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:10.911+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:10.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:10.915+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:10.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 58
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:56:10.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:10.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T11:56:29.447+0000] {processor.py:161} INFO - Started process (PID=1997) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:29.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:29.452+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:29.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:29.456+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:29.455+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 27
    data.append(r.text)
    ^
IndentationError: unexpected indent
[2024-11-06T11:56:29.456+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:29.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T11:56:42.392+0000] {processor.py:161} INFO - Started process (PID=2049) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:42.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:42.396+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:42.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:42.404+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:42.402+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 27
    data.append(r.text)
    ^
IndentationError: unexpected indent
[2024-11-06T11:56:42.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:42.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T11:56:46.021+0000] {processor.py:161} INFO - Started process (PID=2065) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:46.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:46.026+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:46.025+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:46.032+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:46.030+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 27
    data.append(r.text)
    ^
IndentationError: unexpected indent
[2024-11-06T11:56:46.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:46.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T11:56:55.185+0000] {processor.py:161} INFO - Started process (PID=2074) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:55.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:55.189+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:55.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:55.194+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:55.192+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 27
    data.append(r.text)
    ^
IndentationError: unexpected indent
[2024-11-06T11:56:55.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:55.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T11:56:57.223+0000] {processor.py:161} INFO - Started process (PID=2075) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:56:57.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:56:57.226+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:57.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:57.230+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:56:57.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 28
    json.dumps(r.text)
    ^
IndentationError: unexpected indent
[2024-11-06T11:56:57.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:56:57.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2024-11-06T11:57:20.741+0000] {processor.py:161} INFO - Started process (PID=2152) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:57:20.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:57:20.746+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:20.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:20.751+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:20.749+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 28
    json.dumps()
    ^
IndentationError: unexpected indent
[2024-11-06T11:57:20.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:20.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2024-11-06T11:57:25.826+0000] {processor.py:161} INFO - Started process (PID=2153) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:57:25.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:57:25.832+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:25.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:25.836+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:25.835+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 64
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:57:25.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:25.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.054 seconds
[2024-11-06T11:57:32.468+0000] {processor.py:161} INFO - Started process (PID=2160) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:57:32.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:57:32.472+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:32.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:32.478+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:32.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:57:32.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:32.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.052 seconds
[2024-11-06T11:57:47.858+0000] {processor.py:161} INFO - Started process (PID=2223) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:57:47.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:57:47.863+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:47.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:47.868+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:57:47.866+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 63
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:57:47.868+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:57:47.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T11:58:18.510+0000] {processor.py:161} INFO - Started process (PID=2298) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:58:18.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:58:18.514+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:18.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:18.519+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:18.518+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 63
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:58:18.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:18.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.059 seconds
[2024-11-06T11:58:49.274+0000] {processor.py:161} INFO - Started process (PID=2374) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:58:49.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:58:49.280+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:49.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:49.285+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:49.283+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 63
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:58:49.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:49.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.056 seconds
[2024-11-06T11:58:55.409+0000] {processor.py:161} INFO - Started process (PID=2384) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:58:55.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:58:55.414+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:55.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:55.421+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:55.420+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 63
    Cette tâche doit stocker les données au format json dans un fichier dont le nom correspond
    ^
IndentationError: expected an indented block
[2024-11-06T11:58:55.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:55.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T11:58:57.433+0000] {processor.py:161} INFO - Started process (PID=2385) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:58:57.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:58:57.438+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:57.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:57.442+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:58:57.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 24
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:58:57.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:58:57.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T11:59:18.881+0000] {processor.py:161} INFO - Started process (PID=2450) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:59:18.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:59:18.886+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:18.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:18.890+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:18.889+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:59:18.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:18.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.051 seconds
[2024-11-06T11:59:22.671+0000] {processor.py:161} INFO - Started process (PID=2463) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:59:22.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:59:22.678+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:22.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:22.685+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:22.684+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:59:22.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:22.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.065 seconds
[2024-11-06T11:59:24.689+0000] {processor.py:161} INFO - Started process (PID=2464) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:59:24.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:59:24.694+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:24.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:24.699+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:24.697+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:59:24.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:24.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T11:59:36.695+0000] {processor.py:161} INFO - Started process (PID=2489) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:59:36.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:59:36.701+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:36.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:36.707+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:36.705+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:59:36.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:36.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.060 seconds
[2024-11-06T11:59:47.888+0000] {processor.py:161} INFO - Started process (PID=2524) to work on /opt/airflow/dags/get_data.py
[2024-11-06T11:59:47.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T11:59:47.893+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:47.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:47.900+0000] {logging_mixin.py:188} INFO - [2024-11-06T11:59:47.898+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T11:59:47.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T11:59:47.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.062 seconds
[2024-11-06T12:00:07.683+0000] {processor.py:161} INFO - Started process (PID=2566) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:07.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:07.689+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:07.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:07.694+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:07.693+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:07.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:07.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.059 seconds
[2024-11-06T12:00:08.639+0000] {processor.py:161} INFO - Started process (PID=2576) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:08.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:08.644+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:08.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:08.649+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:08.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:08.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:08.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.052 seconds
[2024-11-06T12:00:26.237+0000] {processor.py:161} INFO - Started process (PID=2620) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:26.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:26.242+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:26.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:26.247+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:26.245+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:26.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:26.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2024-11-06T12:00:38.766+0000] {processor.py:161} INFO - Started process (PID=2651) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:38.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:38.772+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:38.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:38.777+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:38.776+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:38.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:38.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T12:00:48.223+0000] {processor.py:161} INFO - Started process (PID=2678) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:48.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:48.228+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:48.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:48.232+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:48.231+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:48.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:48.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.064 seconds
[2024-11-06T12:00:50.682+0000] {processor.py:161} INFO - Started process (PID=2684) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:50.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:50.686+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:50.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:50.690+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:50.689+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:50.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:50.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2024-11-06T12:00:53.822+0000] {processor.py:161} INFO - Started process (PID=2699) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:53.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:53.827+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:53.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:53.831+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:53.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 26
    /app/raw_files
    ^
SyntaxError: invalid syntax
[2024-11-06T12:00:53.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:53.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.047 seconds
[2024-11-06T12:00:57.877+0000] {processor.py:161} INFO - Started process (PID=2700) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:00:57.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:00:57.880+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:57.880+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:57.885+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:00:57.884+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:00:57.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:00:57.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:01:04.061+0000] {processor.py:161} INFO - Started process (PID=2702) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:04.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:04.066+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:04.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:04.071+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:04.069+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:04.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:04.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.058 seconds
[2024-11-06T12:01:07.858+0000] {processor.py:161} INFO - Started process (PID=2718) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:07.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:07.864+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:07.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:07.868+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:07.867+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:07.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:07.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2024-11-06T12:01:12.810+0000] {processor.py:161} INFO - Started process (PID=2744) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:12.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:12.815+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:12.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:12.819+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:12.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:12.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:12.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T12:01:15.662+0000] {processor.py:161} INFO - Started process (PID=2756) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:15.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:15.666+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:15.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:15.670+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:15.669+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:15.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:15.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:01:19.264+0000] {processor.py:161} INFO - Started process (PID=2762) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:19.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:19.268+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:19.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:19.273+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:19.272+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:19.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:19.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:01:21.294+0000] {processor.py:161} INFO - Started process (PID=2763) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:21.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:21.301+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:21.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:21.307+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:21.306+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:21.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:21.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.051 seconds
[2024-11-06T12:01:25.081+0000] {processor.py:161} INFO - Started process (PID=2781) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:25.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:25.085+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:25.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:25.089+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:25.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:25.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:25.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:01:29.125+0000] {processor.py:161} INFO - Started process (PID=2782) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:29.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:29.129+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:29.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:29.133+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:29.132+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:29.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:29.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:01:32.252+0000] {processor.py:161} INFO - Started process (PID=2784) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:32.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:32.255+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:32.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:32.259+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:32.258+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:32.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:32.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T12:01:35.292+0000] {processor.py:161} INFO - Started process (PID=2785) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:35.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:35.297+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:35.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:35.302+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:35.301+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:35.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:35.339+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T12:01:41.432+0000] {processor.py:161} INFO - Started process (PID=2821) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:41.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:41.437+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:41.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:41.444+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:41.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 13
    result = dict(}
                  ^
SyntaxError: closing parenthesis '}' does not match opening parenthesis '('
[2024-11-06T12:01:41.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:41.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.085 seconds
[2024-11-06T12:01:47.386+0000] {processor.py:161} INFO - Started process (PID=2840) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:47.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:47.390+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:47.400+0000] {processor.py:840} INFO - DAG(s) 'openweatherdata_dag' retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:47.627+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.626+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:openweatherdata_dag
[2024-11-06T12:01:47.653+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.652+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:openweatherdata_dag
[2024-11-06T12:01:47.674+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.673+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:openweatherdata_dag
[2024-11-06T12:01:47.675+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.675+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-11-06T12:01:47.704+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.703+0000] {dag.py:3058} INFO - Creating ORM DAG for openweatherdata_dag
[2024-11-06T12:01:47.726+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:47.726+0000] {dag.py:3823} INFO - Setting next_dagrun for openweatherdata_dag to 2024-11-06 12:01:30+00:00, run_after=2024-11-06 12:01:40+00:00
[2024-11-06T12:01:47.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.382 seconds
[2024-11-06T12:01:52.835+0000] {processor.py:161} INFO - Started process (PID=2863) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:01:52.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:01:52.840+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:52.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:52.850+0000] {processor.py:840} INFO - DAG(s) 'openweatherdata_dag' retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:01:52.869+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:52.869+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-11-06T12:01:52.908+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:01:52.908+0000] {dag.py:3823} INFO - Setting next_dagrun for openweatherdata_dag to 2024-11-06 12:01:40+00:00, run_after=2024-11-06 12:01:50+00:00
[2024-11-06T12:01:52.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.108 seconds
[2024-11-06T12:02:01.097+0000] {processor.py:161} INFO - Started process (PID=2865) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:01.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:01.103+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:01.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:01.133+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:01.123+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 33, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-11-06T12:02:01.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:01.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.102 seconds
[2024-11-06T12:02:03.099+0000] {processor.py:161} INFO - Started process (PID=2867) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:03.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:03.103+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:03.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:03.109+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:03.108+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 33, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-11-06T12:02:03.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:03.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:02:17.603+0000] {processor.py:161} INFO - Started process (PID=2919) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:17.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:17.611+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:17.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:17.618+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:17.616+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 33, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-11-06T12:02:17.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:17.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.105 seconds
[2024-11-06T12:02:24.233+0000] {processor.py:161} INFO - Started process (PID=2943) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:24.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:24.237+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:24.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:24.243+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:24.242+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 34, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-11-06T12:02:24.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:24.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.053 seconds
[2024-11-06T12:02:26.294+0000] {processor.py:161} INFO - Started process (PID=2944) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:26.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:26.299+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:26.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:26.308+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:26.306+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 36, in <module>
    with DAG(
NameError: name 'DAG' is not defined
[2024-11-06T12:02:26.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:26.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.057 seconds
[2024-11-06T12:02:29.420+0000] {processor.py:161} INFO - Started process (PID=2946) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:29.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:29.427+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:29.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:29.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:29.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.053 seconds
[2024-11-06T12:02:38.179+0000] {processor.py:161} INFO - Started process (PID=2961) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:38.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:38.183+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:38.182+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:38.187+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:38.186+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:38.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:38.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T12:02:48.417+0000] {processor.py:161} INFO - Started process (PID=2999) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:48.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:48.422+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:48.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:48.427+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:48.426+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:48.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:48.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.047 seconds
[2024-11-06T12:02:50.563+0000] {processor.py:161} INFO - Started process (PID=3006) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:50.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:50.572+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:50.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:50.578+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:50.575+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:50.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:50.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.058 seconds
[2024-11-06T12:02:52.688+0000] {processor.py:161} INFO - Started process (PID=3016) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:52.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:52.691+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:52.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:52.696+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:52.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:52.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:52.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.051 seconds
[2024-11-06T12:02:54.726+0000] {processor.py:161} INFO - Started process (PID=3026) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:54.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:54.730+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:54.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:54.745+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:54.734+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:54.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:54.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.094 seconds
[2024-11-06T12:02:57.814+0000] {processor.py:161} INFO - Started process (PID=3027) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:02:57.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:02:57.818+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:57.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:57.823+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:02:57.822+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:02:57.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:02:57.858+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T12:03:00.633+0000] {processor.py:161} INFO - Started process (PID=3029) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:00.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:00.635+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:00.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:00.640+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:00.639+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:00.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:00.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:03:02.677+0000] {processor.py:161} INFO - Started process (PID=3030) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:02.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:02.690+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:02.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:02.697+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:02.696+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:02.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:02.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.058 seconds
[2024-11-06T12:03:04.793+0000] {processor.py:161} INFO - Started process (PID=3032) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:04.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:04.796+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:04.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:04.801+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:04.799+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:04.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:04.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.056 seconds
[2024-11-06T12:03:07.380+0000] {processor.py:161} INFO - Started process (PID=3045) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:07.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:07.383+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:07.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:07.388+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:07.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:07.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:07.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2024-11-06T12:03:10.230+0000] {processor.py:161} INFO - Started process (PID=3054) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:10.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:10.233+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:10.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:10.239+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:10.238+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:10.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:10.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2024-11-06T12:03:11.729+0000] {processor.py:161} INFO - Started process (PID=3068) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:11.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:11.733+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:11.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:11.739+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:11.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:11.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:11.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.064 seconds
[2024-11-06T12:03:13.371+0000] {processor.py:161} INFO - Started process (PID=3073) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:13.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:13.373+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:13.373+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:13.378+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:13.377+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:13.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:13.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:03:15.851+0000] {processor.py:161} INFO - Started process (PID=3079) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:15.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:15.854+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:15.854+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:15.859+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:15.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:15.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:15.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T12:03:17.804+0000] {processor.py:161} INFO - Started process (PID=3089) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:17.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:17.807+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:17.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:17.811+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:17.810+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:17.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:17.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:03:20.375+0000] {processor.py:161} INFO - Started process (PID=3096) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:20.377+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:20.378+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:20.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:20.383+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:20.381+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:20.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:20.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:03:22.196+0000] {processor.py:161} INFO - Started process (PID=3098) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:22.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:22.199+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:22.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:22.205+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:22.204+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 62
    2024-11-06 12:02:31.237541
             ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[2024-11-06T12:03:22.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:22.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:03:25.897+0000] {processor.py:161} INFO - Started process (PID=3116) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:25.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:25.900+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:25.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:25.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:25.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:03:48.710+0000] {processor.py:161} INFO - Started process (PID=3167) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:48.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:48.714+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:48.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:48.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:48.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2024-11-06T12:03:50.936+0000] {processor.py:161} INFO - Started process (PID=3170) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:03:50.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:03:50.940+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:03:50.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:50.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:03:50.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:04:00.677+0000] {processor.py:161} INFO - Started process (PID=3195) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:04:00.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:04:00.721+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:04:00.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:00.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:00.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.198 seconds
[2024-11-06T12:04:04.714+0000] {processor.py:161} INFO - Started process (PID=3198) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:04:04.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:04:04.717+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:04:04.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:04.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:04.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:04:09.093+0000] {processor.py:161} INFO - Started process (PID=3210) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:04:09.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:04:09.096+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:04:09.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:09.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:09.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:04:11.385+0000] {processor.py:161} INFO - Started process (PID=3215) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:04:11.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:04:11.387+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:04:11.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:11.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:11.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2024-11-06T12:04:41.689+0000] {processor.py:161} INFO - Started process (PID=3292) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:04:41.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:04:41.692+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:04:41.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:41.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:04:41.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:05:12.024+0000] {processor.py:161} INFO - Started process (PID=3369) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:05:12.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:05:12.028+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:05:12.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:05:12.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:05:12.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.035 seconds
[2024-11-06T12:05:42.297+0000] {processor.py:161} INFO - Started process (PID=3446) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:05:42.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:05:42.300+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:05:42.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:05:42.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:05:42.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:06:12.766+0000] {processor.py:161} INFO - Started process (PID=3524) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:06:12.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:06:12.769+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:06:12.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:06:12.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:06:12.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:06:43.332+0000] {processor.py:161} INFO - Started process (PID=3601) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:06:43.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:06:43.336+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:06:43.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:06:43.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:06:43.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:07:13.922+0000] {processor.py:161} INFO - Started process (PID=3677) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:07:13.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:07:13.925+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:07:13.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:07:13.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:07:13.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:07:44.452+0000] {processor.py:161} INFO - Started process (PID=3754) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:07:44.453+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:07:44.454+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:07:44.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:07:44.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:07:44.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:08:14.902+0000] {processor.py:161} INFO - Started process (PID=3832) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:08:14.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:08:14.907+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:08:14.907+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:08:14.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:08:14.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.049 seconds
[2024-11-06T12:08:45.104+0000] {processor.py:161} INFO - Started process (PID=3910) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:08:45.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:08:45.106+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:08:45.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:08:45.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:08:45.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:09:15.300+0000] {processor.py:161} INFO - Started process (PID=3986) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:09:15.303+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:09:15.304+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:09:15.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:09:15.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:09:15.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2024-11-06T12:09:46.032+0000] {processor.py:161} INFO - Started process (PID=4063) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:09:46.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:09:46.035+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:09:46.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:09:46.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:09:46.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:10:16.360+0000] {processor.py:161} INFO - Started process (PID=4140) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:10:16.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:10:16.362+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:10:16.362+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:10:16.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:10:16.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:10:46.801+0000] {processor.py:161} INFO - Started process (PID=4217) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:10:46.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:10:46.804+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:10:46.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:10:46.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:10:46.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:11:17.666+0000] {processor.py:161} INFO - Started process (PID=4294) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:11:17.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:11:17.668+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:11:17.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:11:17.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:11:17.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.254 seconds
[2024-11-06T12:11:48.919+0000] {processor.py:161} INFO - Started process (PID=4370) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:11:48.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:11:48.922+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:11:48.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:11:48.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:11:48.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:12:19.243+0000] {processor.py:161} INFO - Started process (PID=4447) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:12:19.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:12:19.246+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:12:19.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:12:19.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:12:19.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:12:49.438+0000] {processor.py:161} INFO - Started process (PID=4523) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:12:49.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:12:49.441+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:12:49.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:12:49.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:12:49.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:13:19.805+0000] {processor.py:161} INFO - Started process (PID=4600) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:13:19.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:13:19.808+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:13:19.807+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:13:19.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:13:19.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:13:50.242+0000] {processor.py:161} INFO - Started process (PID=4682) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:13:50.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:13:50.247+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:13:50.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:13:50.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:13:50.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:14:20.530+0000] {processor.py:161} INFO - Started process (PID=4760) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:14:20.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:14:20.535+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:14:20.534+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:14:20.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:14:20.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:14:51.001+0000] {processor.py:161} INFO - Started process (PID=4837) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:14:51.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:14:51.005+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:14:51.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:14:51.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:14:51.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:15:21.597+0000] {processor.py:161} INFO - Started process (PID=4914) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:15:21.599+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:15:21.600+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:15:21.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:15:21.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:15:21.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:15:52.109+0000] {processor.py:161} INFO - Started process (PID=4988) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:15:52.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:15:52.113+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:15:52.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:15:52.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:15:52.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:16:22.841+0000] {processor.py:161} INFO - Started process (PID=5064) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:16:22.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:16:22.844+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:16:22.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:16:22.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:16:22.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.056 seconds
[2024-11-06T12:16:53.432+0000] {processor.py:161} INFO - Started process (PID=5140) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:16:53.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:16:53.436+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:16:53.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:16:53.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:16:53.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.066 seconds
[2024-11-06T12:17:24.136+0000] {processor.py:161} INFO - Started process (PID=5217) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:17:24.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:17:24.142+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:17:24.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:17:24.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:17:24.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.067 seconds
[2024-11-06T12:17:54.841+0000] {processor.py:161} INFO - Started process (PID=5295) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:17:54.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:17:54.846+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:17:54.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:17:54.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:17:54.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:18:25.731+0000] {processor.py:161} INFO - Started process (PID=5372) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:18:25.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:18:25.733+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:18:25.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:18:25.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:18:25.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:18:55.966+0000] {processor.py:161} INFO - Started process (PID=5449) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:18:55.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:18:55.970+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:18:55.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:18:55.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:18:56.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2024-11-06T12:19:26.515+0000] {processor.py:161} INFO - Started process (PID=5526) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:19:26.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:19:26.519+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:19:26.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:19:26.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:19:26.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T12:19:56.791+0000] {processor.py:161} INFO - Started process (PID=5604) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:19:56.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:19:56.794+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:19:56.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:19:56.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:19:56.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:20:27.238+0000] {processor.py:161} INFO - Started process (PID=5681) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:20:27.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:20:27.242+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:20:27.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:20:27.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:20:27.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:20:57.803+0000] {processor.py:161} INFO - Started process (PID=5758) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:20:57.805+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:20:57.807+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:20:57.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:20:57.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:20:57.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:21:28.235+0000] {processor.py:161} INFO - Started process (PID=5835) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:21:28.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:21:28.238+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:21:28.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:21:28.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:21:28.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:21:59.146+0000] {processor.py:161} INFO - Started process (PID=5912) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:21:59.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:21:59.150+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:21:59.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:21:59.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:21:59.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:22:29.667+0000] {processor.py:161} INFO - Started process (PID=5989) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:22:29.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:22:29.672+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:22:29.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:22:29.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:22:29.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2024-11-06T12:23:00.306+0000] {processor.py:161} INFO - Started process (PID=6066) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:23:00.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:23:00.310+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:23:00.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:23:00.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:23:00.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:23:30.773+0000] {processor.py:161} INFO - Started process (PID=6143) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:23:30.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:23:30.776+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:23:30.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:23:30.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:23:30.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:24:01.171+0000] {processor.py:161} INFO - Started process (PID=6220) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:24:01.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:24:01.174+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:24:01.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:24:01.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:24:01.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:24:31.646+0000] {processor.py:161} INFO - Started process (PID=6303) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:24:31.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:24:31.649+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:24:31.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:24:31.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:24:31.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.058 seconds
[2024-11-06T12:25:02.022+0000] {processor.py:161} INFO - Started process (PID=6380) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:25:02.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:25:02.026+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:25:02.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:25:02.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:25:02.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2024-11-06T12:25:32.446+0000] {processor.py:161} INFO - Started process (PID=6458) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:25:32.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:25:32.450+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:25:32.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:25:32.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:25:32.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:26:02.800+0000] {processor.py:161} INFO - Started process (PID=6535) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:26:02.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:26:02.803+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:26:02.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:26:02.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:26:02.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:26:33.097+0000] {processor.py:161} INFO - Started process (PID=6610) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:26:33.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:26:33.101+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:26:33.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:26:33.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:26:33.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:27:03.741+0000] {processor.py:161} INFO - Started process (PID=6687) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:27:03.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:27:03.744+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:27:03.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:27:03.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:27:03.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:27:34.168+0000] {processor.py:161} INFO - Started process (PID=6765) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:27:34.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:27:34.179+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:27:34.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:27:34.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:27:34.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.070 seconds
[2024-11-06T12:28:04.990+0000] {processor.py:161} INFO - Started process (PID=6842) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:28:04.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:28:04.993+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:28:04.993+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:28:04.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:28:05.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T12:28:35.314+0000] {processor.py:161} INFO - Started process (PID=6920) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:28:35.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:28:35.317+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:28:35.317+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:28:35.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:28:35.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.054 seconds
[2024-11-06T12:29:05.840+0000] {processor.py:161} INFO - Started process (PID=6997) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:29:05.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:29:05.844+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:29:05.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:29:05.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:29:05.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2024-11-06T12:29:36.428+0000] {processor.py:161} INFO - Started process (PID=7074) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:29:36.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:29:36.431+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:29:36.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:29:36.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:29:36.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:30:06.549+0000] {processor.py:161} INFO - Started process (PID=7151) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:30:06.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:30:06.553+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:30:06.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:30:06.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:30:06.579+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:30:36.669+0000] {processor.py:161} INFO - Started process (PID=7224) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:30:36.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:30:36.672+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:30:36.672+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:30:36.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:30:36.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:31:07.152+0000] {processor.py:161} INFO - Started process (PID=7302) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:31:07.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:31:07.158+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:31:07.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:31:07.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:31:07.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.059 seconds
[2024-11-06T12:31:37.685+0000] {processor.py:161} INFO - Started process (PID=7379) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:31:37.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:31:37.689+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:31:37.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:31:37.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:31:37.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:32:08.286+0000] {processor.py:161} INFO - Started process (PID=7456) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:32:08.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:32:08.289+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:32:08.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:32:08.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:32:08.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:32:38.729+0000] {processor.py:161} INFO - Started process (PID=7533) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:32:38.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:32:38.732+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:32:38.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:32:38.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:32:38.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:33:09.111+0000] {processor.py:161} INFO - Started process (PID=7609) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:33:09.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:33:09.114+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:33:09.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:33:09.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:33:09.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:33:39.581+0000] {processor.py:161} INFO - Started process (PID=7688) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:33:39.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:33:39.585+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:33:39.584+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:33:39.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:33:39.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:34:09.931+0000] {processor.py:161} INFO - Started process (PID=7765) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:34:09.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:34:09.934+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:34:09.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:34:09.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:34:09.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:34:40.356+0000] {processor.py:161} INFO - Started process (PID=7842) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:34:40.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:34:40.365+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:34:40.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:34:40.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:34:40.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2024-11-06T12:35:10.664+0000] {processor.py:161} INFO - Started process (PID=7920) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:35:10.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:35:10.668+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:35:10.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:35:10.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:35:10.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:35:41.012+0000] {processor.py:161} INFO - Started process (PID=7997) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:35:41.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:35:41.015+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:35:41.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:35:41.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:35:41.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2024-11-06T12:36:11.495+0000] {processor.py:161} INFO - Started process (PID=8074) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:36:11.498+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:36:11.500+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:36:11.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:36:11.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:36:11.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.052 seconds
[2024-11-06T12:36:42.120+0000] {processor.py:161} INFO - Started process (PID=8151) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:36:42.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:36:42.122+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:36:42.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:36:42.125+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:36:42.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.035 seconds
[2024-11-06T12:37:12.298+0000] {processor.py:161} INFO - Started process (PID=8227) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:37:12.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:37:12.302+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:37:12.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:37:12.305+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:37:12.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:37:42.818+0000] {processor.py:161} INFO - Started process (PID=8303) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:37:42.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:37:42.821+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:37:42.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:37:42.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:37:42.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T12:38:13.028+0000] {processor.py:161} INFO - Started process (PID=8380) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:38:13.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:38:13.031+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:38:13.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:38:13.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:38:13.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:38:43.418+0000] {processor.py:161} INFO - Started process (PID=8458) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:38:43.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:38:43.422+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:38:43.422+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:38:43.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:38:43.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:39:13.960+0000] {processor.py:161} INFO - Started process (PID=8535) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:39:13.962+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:39:13.963+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:39:13.963+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:39:13.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:39:13.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2024-11-06T12:39:44.039+0000] {processor.py:161} INFO - Started process (PID=8612) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:39:44.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:39:44.042+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:39:44.041+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:39:44.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:39:44.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:40:14.182+0000] {processor.py:161} INFO - Started process (PID=8689) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:40:14.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:40:14.184+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:40:14.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:40:14.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:40:14.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:40:44.903+0000] {processor.py:161} INFO - Started process (PID=8764) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:40:44.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:40:44.906+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:40:44.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:40:44.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:40:44.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.034 seconds
[2024-11-06T12:41:15.733+0000] {processor.py:161} INFO - Started process (PID=8840) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:41:15.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:41:15.736+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:41:15.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:41:15.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:41:15.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:41:45.947+0000] {processor.py:161} INFO - Started process (PID=8918) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:41:45.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:41:45.950+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:41:45.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:41:45.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:41:45.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.035 seconds
[2024-11-06T12:42:16.561+0000] {processor.py:161} INFO - Started process (PID=8996) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:42:16.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:42:16.575+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:42:16.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:42:16.586+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:42:16.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.070 seconds
[2024-11-06T12:42:46.813+0000] {processor.py:161} INFO - Started process (PID=9075) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:42:46.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:42:46.816+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:42:46.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:42:46.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:42:46.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:43:17.602+0000] {processor.py:161} INFO - Started process (PID=9153) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:43:17.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:43:17.606+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:43:17.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:43:17.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:43:17.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:43:47.952+0000] {processor.py:161} INFO - Started process (PID=9231) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:43:47.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:43:47.956+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:43:47.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:43:47.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:43:47.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2024-11-06T12:44:18.253+0000] {processor.py:161} INFO - Started process (PID=9308) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:44:18.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:44:18.256+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:44:18.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:44:18.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:44:18.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2024-11-06T12:44:48.728+0000] {processor.py:161} INFO - Started process (PID=9384) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:44:48.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:44:48.734+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:44:48.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:44:48.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:44:48.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2024-11-06T12:45:19.065+0000] {processor.py:161} INFO - Started process (PID=9461) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:45:19.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:45:19.068+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:45:19.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:45:19.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:45:19.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.053 seconds
[2024-11-06T12:45:49.242+0000] {processor.py:161} INFO - Started process (PID=9538) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:45:49.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:45:49.245+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:45:49.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:45:49.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:45:49.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2024-11-06T12:46:19.659+0000] {processor.py:161} INFO - Started process (PID=9615) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:46:19.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:46:19.662+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:46:19.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:46:19.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:46:19.703+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2024-11-06T12:46:49.906+0000] {processor.py:161} INFO - Started process (PID=9691) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:46:49.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:46:49.909+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:46:49.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:46:49.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:46:49.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2024-11-06T12:47:20.081+0000] {processor.py:161} INFO - Started process (PID=9768) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:47:20.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:47:20.083+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:47:20.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:47:20.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:47:20.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2024-11-06T12:47:50.391+0000] {processor.py:161} INFO - Started process (PID=9845) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:47:50.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:47:50.394+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:47:50.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:47:50.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:47:50.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2024-11-06T12:48:21.155+0000] {processor.py:161} INFO - Started process (PID=9922) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:48:21.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:48:21.158+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:48:21.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:48:21.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:48:21.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.037 seconds
[2024-11-06T12:48:51.633+0000] {processor.py:161} INFO - Started process (PID=10005) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:48:51.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:48:51.636+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:48:51.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:48:51.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:48:51.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.036 seconds
[2024-11-06T12:49:22.014+0000] {processor.py:161} INFO - Started process (PID=10084) to work on /opt/airflow/dags/get_data.py
[2024-11-06T12:49:22.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2024-11-06T12:49:22.016+0000] {logging_mixin.py:188} INFO - [2024-11-06T12:49:22.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2024-11-06T12:49:22.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2024-11-06T12:49:22.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
